/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { MegaChat } from "./MegaChat";
export * as factories from "./factories";
export { MegaChat__factory } from "./factories/MegaChat__factory";
